export const COURSES_LOADED = "COURSES_LOADED";
export const COURSE_LOADED = "COURSE_LOADED";
export const CHANGE_SELECTED_LECTURE = "CHANGE_SELECTED_LECTURE";
export const ADD_COURSE = "ADD_COURSE";
export const DELETE_COURSE = "DELETE_COURSE";
export const EDIT_COURSE = "EDIT_COURSE";
export const USER_LOADED = "USER_LOADED";

/* STUDENT */
export const STUDENT_ADD_COURSE = "STUDENT_ADD_COURSE";

/* ERROR */
export const ERROR = "ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";

/* USER */
export const LOG_IN = "LOG_IN";
export const LOG_OUT = "LOG_OUT";

/*DASHBOARD CONTENT_TYPE */
export const CHANGE_CONTENT_TYPE = "CHANGE_CONTENT_TYPE"

/*LOADING */
export const SET_LOADING = "SET_LOADING"
export const REMOVE_LOADING = "REMOVE_LOADING"