/* COURSE */
export const STUDENT_ADD_COURSE = "STUDENT_ADD_COURSE";
export const COURSES_LOADED = "COURSES_LOADED";
export const COURSE_LOADED = "COURSE_LOADED";
export const ADD_COURSE = "ADD_COURSE";
export const DELETE_COURSE = "DELETE_COURSE";
export const EDIT_COURSE = "EDIT_COURSE";

/* LECTURE */
export const CHANGE_SELECTED_LECTURE = "CHANGE_SELECTED_LECTURE";
export const ADD_LECTURE = "ADD_LECTURE";
export const SET_LIVE_LECTURE = "SET_LIVE_LECTURE";
export const SET_FULLSCREEN = "SET_FULLSCREEN";
export const EDIT_LECTURE = "EDIT_LECTURE";
export const DELETE_LECTURE = "DELETE_LECTURE";

/*QUIZ*/
export const ADD_QUIZ = "ADD_QUIZ";
export const SET_ANSWER = "SET_ANSWER"
export const REMOVE_ANSWER = "REMOVE_ANSWER";
export const REMOVE_ANSWERS = "REMOVE_ANSWERS"
export const SET_CORRECT_ANSWER = "SET_CORRECT_ANSWER"
export const EDIT_QUIZ = "EDIT_QUIZ";
export const DELETE_QUIZ = "DELETE_QUIZ"
export const SET_LIVE_QUIZ = "SET_LIVE_QUIZ";

/* ERROR */
export const ERROR = "ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";

/* USER */
export const LOG_IN = "LOG_IN";
export const LOG_OUT = "LOG_OUT";
export const SIGN_UP = "SIGN_UP";
export const USER_LOADED = "USER_LOADED";
export const EDIT_USER = "EDIT_USER";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const DELETE_USER= "DELETE_USER";

/*DASHBOARD CONTENT_TYPE */
export const CHANGE_CONTENT_TYPE = "CHANGE_CONTENT_TYPE"

/*LOADING */
export const SET_LOADING = "SET_LOADING"
export const REMOVE_LOADING = "REMOVE_LOADING"
export const SET_COMPONENT_LOADING = "SET_COMPONENT_LOADING"
export const REMOVE_COMPONENT_LOADING = "REMOVE_COMPONENT_LOADING"